# Generated by Django 6.1 on 2026-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('customers', '0002_customer_cust_email_idx'),
        ('pricing', '0001_initial'),
        ('quotations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('converted', 'Converted to Order')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', '-created_at'], name='quot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', '-created_at'], name='quot_customer_idx'),
        ),
    ]
