"""
Django settings for scholarlywriters_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Fix SSL certificate verification on Windows / Python 3.14+
try:
    import certifi
    os.environ.setdefault('SSL_CERT_FILE', certifi.where())
except ImportError:
    pass

from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR.parent

# --- SECRET KEY ---
# Fail loudly in production if the secret key is still the insecure default.
_secret = config('SECRET_KEY', default='')
if not _secret or _secret.startswith('django-insecure'):
    if not config('DEBUG', default=False, cast=bool):
        raise ValueError('Set a strong SECRET_KEY in .env for production!')
SECRET_KEY = _secret or 'django-insecure-dev-only-key'

# --- DEBUG ---
DEBUG = config('DEBUG', default=False, cast=bool)

# --- ALLOWED HOSTS ---
ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'accounts',
    'currencies',
    'customers',
    'notifications',
    'orders',
    'payments',
    'pricing',
    'quotations',
    'services',
    'samples',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'scholarlywriters_backend.middleware.SecurityHeadersMiddleware',
    'scholarlywriters_backend.middleware.AdminLoginThrottleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scholarlywriters_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', FRONTEND_DIR] if FRONTEND_DIR.exists() else [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scholarlywriters_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model

AUTH_USER_MODEL = 'accounts.CustomUser'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '120/minute',
        'quotation_create': '10/hour',
        'payment_create': '10/hour',
        'payment_execute': '10/hour',
        'calculate_price': '30/minute',
        'contact_create': '10/hour',
    },
}


# CORS
# https://github.com/adamchainz/django-cors-headers
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config('CORS_ALLOWED_ORIGINS', default='').split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS']
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
]


# CSRF Trusted Origins (required for cross-origin POSTs)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config('CSRF_TRUSTED_ORIGINS', default='').split(',')
    if origin.strip()
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/
EMAIL_BACKEND = 'scholarlywriters_backend.email_backend.SSLFriendlyEmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
BUSINESS_EMAIL = config('BUSINESS_EMAIL', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=config('EMAIL_HOST_USER', default=''))


# WhatsApp Business API

WHATSAPP_API_URL = config('WHATSAPP_API_URL', default='')
WHATSAPP_API_TOKEN = config('WHATSAPP_API_TOKEN', default='')


# PayPal

PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')


# Exchange Rate API

EXCHANGE_RATE_API_KEY = config('EXCHANGE_RATE_API_KEY', default='')
EXCHANGE_RATE_API_URL = config('EXCHANGE_RATE_API_URL', default='https://v6.exchangerate-api.com/v6')


# Frontend URL
FRONTEND_URL = config('FRONTEND_URL', default='http://127.0.0.1:8000')


# --- Cache (used by admin throttle and other caching) ---
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# --- Security Headers (production) ---
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # JS needs to read csrftoken for X-CSRFToken header
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session / CSRF cookie age (1 week)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
CSRF_COOKIE_AGE = 60 * 60 * 24 * 7


# --- File Upload Limits ---
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024    # 10 MB
ALLOWED_UPLOAD_EXTENSIONS = {'.pdf', '.docx', '.doc', '.txt', '.rtf'}


# --- Logging ---
_LOG_DIR = Path(config('LOG_DIR', default=str(BASE_DIR / 'logs')))
try:
    os.makedirs(_LOG_DIR, exist_ok=True)
    _LOG_FILE = _LOG_DIR / 'django.log'
except (OSError, PermissionError):
    _LOG_FILE = None

_handlers = ['console']
_handler_defs = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
}
if _LOG_FILE:
    _handlers.append('file')
    _handler_defs['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(_LOG_FILE),
        'maxBytes': 5 * 1024 * 1024,  # 5 MB
        'backupCount': 5,
        'formatter': 'verbose',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': _handler_defs,
    'loggers': {
        'django': {
            'handlers': _handlers,
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': _handlers,
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security.login': {
            'handlers': _handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'quotations': {
            'handlers': _handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': _handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'contact': {
            'handlers': _handlers,
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# --- Admin Login Throttling ---
# Fail2ban-compatible: track failed admin logins.
ADMIN_LOGIN_ATTEMPTS_ALLOWED = 5
ADMIN_LOGIN_LOCKOUT_SECONDS = 900  # 15 minutes
