# Generated by Django 6.1 on 2026-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', '-created_at'], name='notif_status_idx'),
        ),
    ]
