"""
Django settings for gbv project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import base64
import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!tbx2n)=g2uze9=(@w8751-nkib0l6$a755h)@&60+zs!!tn6^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'public',
    'notifications',
    'cases',
    'admin_panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gbv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project‑level templates folder (optional but recommended)
        'DIRS': [BASE_DIR / 'templates'],
        # App‑level templates are automatically discovered because APP_DIRS=True
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Makes {{ MEDIA_URL }} available in all templates
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'gbv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Additional locations of static files (project‑level)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Folder where collected static files will be stored (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (user‑uploaded files)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "cases:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

# Web Push (VAPID) keys for sending notifications to subscribed browsers.
# VAPID_PUBLIC_KEY is read by the public status page ("Get notified" button);
# VAPID_PRIVATE_KEY signs the push requests server-side (pywebpush).
#
# In production set both via environment variables. In development the keys are
# generated once on first run and persisted to .vapid_keys.json (gitignored),
# so every developer gets working push notifications with no configuration.
# Generate a fresh pair manually with `vapid --gen` (from the py-vapid CLI).
def _load_vapid_keys():
    public_key = os.environ.get("VAPID_PUBLIC_KEY")
    private_key = os.environ.get("VAPID_PRIVATE_KEY")
    if public_key and private_key:
        return public_key, private_key

    keys_file = BASE_DIR / ".vapid_keys.json"
    if keys_file.exists():
        data = json.loads(keys_file.read_text())
        return data["public_key"], data["private_key"]

    from cryptography.hazmat.primitives import serialization
    from py_vapid import Vapid

    vapid = Vapid()
    vapid.generate_keys()
    public_key = base64.urlsafe_b64encode(
        vapid.public_key.public_bytes(
            serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
        )
    ).rstrip(b"=").decode()
    private_key = vapid.private_pem().decode()
    keys_file.write_text(
        json.dumps({"public_key": public_key, "private_key": private_key}, indent=2)
    )
    return public_key, private_key

VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY = _load_vapid_keys()
VAPID_ADMIN_EMAIL = os.environ.get("VAPID_ADMIN_EMAIL", "notifications@amani.local")

# In development, print emails to the console instead of trying to send them
# over SMTP (which fails without a mail server).
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# config/settings.py
RATELIMIT_ENABLE = True
RATELIMIT_VIEW = "public.views.ratelimited_view"  # optional custom 429 page