# Generated by Django 6.1 on 2026-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField()),
                ('format', models.CharField(help_text='Citation format, e.g. APA, MLA, Harvard', max_length=50)),
                ('file', models.FileField(upload_to='samples/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('essay', 'Essay'), ('research', 'Research Paper'), ('dissertation', 'Dissertation'), ('case-study', 'Case Study')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Samples',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
