# Generated by Django 6.1 on 2026-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['category', 'is_active'], name='sample_cat_active_idx'),
        ),
    ]
