# Generated by Django 6.1 on 2026-08-11 10:01

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=cases.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('tracking_code_hash', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_of_incident', models.DateField(blank=True, null=True)),
                ('approximate_time', models.CharField(blank=True, help_text="e.g. 'Morning', 'Around 8pm', 'Not sure'", max_length=50)),
                ('platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('x_twitter', 'X (Twitter)'), ('telegram', 'Telegram'), ('sms_call', 'SMS / Phone Call'), ('email', 'Email'), ('dating_app', 'Dating App'), ('other', 'Other'), ('n/a', 'Not applicable')], max_length=20)),
                ('platform_other', models.CharField(blank=True, max_length=100)),
                ('location_context', models.CharField(blank=True, help_text='Physical location or online context', max_length=255)),
                ('relationship_to_perpetrator', models.CharField(blank=True, choices=[('stranger', 'Stranger'), ('acquaintance', 'Acquaintance'), ('friend', 'Friend'), ('family', 'Family member'), ('partner', 'Current/former intimate partner'), ('colleague', 'Colleague/Classmate'), ('unknown', 'Unknown/Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('perpetrator_name', models.CharField(blank=True, max_length=255)),
                ('perpetrator_username', models.CharField(blank=True, max_length=255)),
                ('perpetrator_profile_url', models.URLField(blank=True, max_length=500)),
                ('perpetrator_contact', models.CharField(blank=True, max_length=255)),
                ('perpetrator_additional_info', models.TextField(blank=True)),
                ('contact_method', models.CharField(choices=[('none', "No contact / don't notify"), ('email', 'Email'), ('phone', 'Phone (SMS)')], default='none', max_length=10)),
                ('contact_value', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_handler', models.ForeignKey(blank=True, limit_choices_to={'role': 'case_handler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='cases.casereport')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.casereport')),
            ],
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('handler', 'Case Handler'), ('victim', 'Victim')], max_length=10)),
                ('message', models.TextField()),
                ('visibility', models.CharField(choices=[('victim', 'Visible to victim'), ('internal', 'Internal note only')], default='victim', max_length=10)),
                ('is_read_by_victim', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.casereport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
