# Generated by Django 6.1 on 2026-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='tracking_code_hash',
            field=models.CharField(max_length=255),
        ),
    ]
